//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmTag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlarmTag()
        {
            this.AlarmEvents = new HashSet<AlarmEvent>();
            this.AlarmValues = new HashSet<AlarmValue>();
        }
    
        public int PlcId { get; set; }
        public int TagId { get; set; }
        public string Name { get; set; }
        public Nullable<float> LowAlarm { get; set; }
        public Nullable<float> HighAlarm { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmEvent> AlarmEvents { get; set; }
        public virtual PLC PLC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlarmValue> AlarmValues { get; set; }
    }
}
