//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmEvent
    {
        public int PlcId { get; set; }
        public int TagId { get; set; }
        public System.DateTime Datetime { get; set; }
        public bool AlarmIn { get; set; }
    
        public virtual AlarmTag AlarmTag { get; set; }
    }
}
