//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLogTag
    {
        public DataLogTag()
        {
            this.DataLog_Float = new HashSet<DataLogFloat>();
        }
    
        public string TagName { get; set; }
        public short TagIndex { get; set; }
        public Nullable<short> TagType { get; set; }
        public Nullable<short> TagDataType { get; set; }
        public int ProjectId { get; set; }
    
        public virtual ICollection<DataLogFloat> DataLog_Float { get; set; }
    }
}
