//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLogFloat
    {
        public System.DateTime DateTime { get; set; }
        public short Msec { get; set; }
        public short TagIndex { get; set; }
        public Nullable<double> Value { get; set; }
        public string Status { get; set; }
        public string Marker { get; set; }
        public int ProjectId { get; set; }
    
        public virtual DataLogTag DataLog_Tag { get; set; }
    }
}
