//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataLogEntities : DbContext
    {
        public DataLogEntities()
            : base("name=DataLogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataLogAlarm> DataLogAlarms { get; set; }
        public virtual DbSet<DataLogFloat> DataLogFloats { get; set; }
        public virtual DbSet<DataLogTag> DataLogTags { get; set; }
    }
}
