//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLogAlarm
    {
        public System.DateTime DateTime { get; set; }
        public short Militime { get; set; }
        public string TransType { get; set; }
        public string TagName { get; set; }
        public Nullable<double> TagValue { get; set; }
        public string TagType { get; set; }
        public Nullable<double> ThreshVal { get; set; }
        public Nullable<byte> ThreshNum { get; set; }
        public string ThreshLabl { get; set; }
        public Nullable<byte> Severity { get; set; }
        public string DstFlag { get; set; }
        public string UserId { get; set; }
        public Nullable<byte> AlarmType { get; set; }
        public string Dscription { get; set; }
        public string UserStn { get; set; }
        public string LoggingStn { get; set; }
        public int WorkstationId { get; set; }
        public int ProjectId { get; set; }
    }
}
