//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PcEvent
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Message { get; set; }
        public int WorkstationId { get; set; }
        public int Level { get; set; }
    
        public virtual Workstation Workstation { get; set; }
    }
}
