//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLC
    {
        public PLC()
        {
            this.Events = new HashSet<PlcEvent>();
            this.EventsOlds = new HashSet<PlcEventsOld>();
            this.Messages = new HashSet<PlcMessage>();
            this.PLC_TO = new HashSet<PLC_TO>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> PlcTypeId { get; set; }
        public Nullable<int> FactoryId { get; set; }
        public string Topic { get; set; }
        public Nullable<int> ProtocolType { get; set; }
        public Nullable<int> LastEventIndex { get; set; }
        public Nullable<System.DateTime> LastEventDateTime { get; set; }
        public Nullable<int> LastEventMsec { get; set; }
        public Nullable<int> Faults { get; set; }
        public string href { get; set; }
        public Nullable<int> OpcDataLoggerId { get; set; }
        public int PositionNumber { get; set; }
        public Nullable<bool> Disassembled { get; set; }
    
        public virtual ICollection<PlcEvent> Events { get; set; }
        public virtual ICollection<PlcEventsOld> EventsOlds { get; set; }
        public virtual Factory Factory { get; set; }
        public virtual ICollection<PlcMessage> Messages { get; set; }
        public virtual PLCDescription PLC_Description { get; set; }
        public virtual ICollection<PLC_TO> PLC_TO { get; set; }
    }
}
