//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLCDescription
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameFull { get; set; }
        public string Position { get; set; }
        public string Adress { get; set; }
        public string SerialNumber { get; set; }
        public string Inn { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
    
        public virtual PLC PLC { get; set; }
    }
}
