//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlcMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlcMessage()
        {
            this.PlcEvents = new HashSet<PlcEvent>();
            this.PlcOldEvents = new HashSet<PlcOldEvent>();
        }
    
        public int PlcId { get; set; }
        public int Number { get; set; }
        public string Text { get; set; }
        public Nullable<short> Group { get; set; }
        public Nullable<int> Severity { get; set; }
    
        public virtual PLC PLC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlcEvent> PlcEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlcOldEvent> PlcOldEvents { get; set; }
    }
}
