//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workstation
    {
        public Workstation()
        {
            this.Events_Pc = new HashSet<PcEvent>();
            this.Ws_Data = new HashSet<Ws_Data>();
        }
    
        public int Id { get; set; }
        public int FactoryId { get; set; }
        public int Number { get; set; }
        public int ProjectId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string IP { get; set; }
        public byte Enable { get; set; }
        public string NetworkName { get; set; }
        public Nullable<long> MAC { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<PcEvent> Events_Pc { get; set; }
        public virtual ICollection<Ws_Data> Ws_Data { get; set; }
    }
}
