//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workstation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workstation()
        {
            this.Events_Pc = new HashSet<PcEvent>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FactoryId { get; set; }
        public int Number { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string IP { get; set; }
        public byte Enable { get; set; }
        public string NetworkName { get; set; }
        public string MAC { get; set; }
        public Nullable<bool> UseMstsc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PcEvent> Events_Pc { get; set; }
        public virtual ProjectHMI Project { get; set; }
    }
}
