//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ws_Data
    {
        public int id { get; set; }
        public int WorkstationId { get; set; }
        public long status { get; set; }
        public string active_window { get; set; }
        public string work_time { get; set; }
        public string activity { get; set; }
        public long CPU { get; set; }
        public long MB { get; set; }
        public long HDD { get; set; }
        public long GPU { get; set; }
        public long Fan { get; set; }
        public long GPUFan { get; set; }
    
        public virtual Workstation Workstation { get; set; }
    }
}
